### ISSUE TITLE
[Website] Broken OG images

### ISSUE THREAD

**Issue by smoya** [asyncapi/modelina#1165]
#### Describe the bug
The OG (Open Graph) images are broken. 

That means sharing the website URL on social media won't have images as previews.

See the following meta tag on the [Modelina website source code](view-source:https://modelina.org):

```html
<meta property="og:url" content="https://master--modelina.netlify.app/"/><meta property="og:image" content="https://master--modelina.netlify.app/img/social/modelina-card.jpg"/>
```

As you can check, the link is broken.

**Comment by sambhavgupta0705** [comment]
@smoya can you please elaborate this issue please

**Comment by smoya** [comment]
> @smoya can you please elaborate this issue please

Sure! Is the new description better now?

**Comment by sambhavgupta0705** [comment]
okay,Thanks @smoya

**Comment by sambhavgupta0705** [comment]
@jonaslagoni @smoya well this is a netlify fucntions or server error which we are also facing with 404 page.
IMO netlify is considering it as a function so that's why it is giving this error.We can change the link from deploy url to a `normal image` of modelina card present in source code

**Comment by sambhavgupta0705** [comment]
This code worked with main website but will not work with modelina as we are using some different functions here

**Comment by AnishKacham** [comment]
hey, I think this issue is fixed right? 
https://github.com/asyncapi/modelina/blob/68e9a23f607ffd2028aafc84d9f9ab6239cee957/modelina-website/src/components/layouts/Head.tsx#L13

**Comment by smoya** [comment]
> hey @jonaslagoni , I think this issue is fixed, right?
> 
> https://github.com/asyncapi/modelina/blob/68e9a23f607ffd2028aafc84d9f9ab6239cee957/modelina-website/src/components/layouts/Head.tsx#L13

I still see the same issue 
![iTerm2_KUvFSKD5](https://github.com/asyncapi/modelina/assets/1083296/4d777b80-e699-4f03-a53b-483f21606007)

**Comment by smoya** [comment]
Maybe related? https://github.com/asyncapi/website/issues/2639

**Comment by smoya** [comment]
I believe this should stay open until fixed
